FROM nginx

# COPY nginx.conf /etc/nginx/conf.d/nginx.conf
# COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
# COPY nginx.conf /etc/nginx/sites-enabled/default/

RUN mkdir -p /etc/nginx/html/
RUN echo "hello" > /etc/nginx/html/index.html
